image: gmacario/build-yocto

# TODO: remove the SSL variable afterwards
variables:
  GIT_SUBMODULE_STRATEGY: 'recursive'
  GIT_SSL_NO_VERIFY: 'true'
  BITBAKEDIR: '$CI_PROJECT_DIR/bitbake'

# TODO:
# add stages:
# - build 2 versions in parallel (ARM and x86-64)
# - run a VM and security scan
# - deploy the image somewhere
stages:
  - setup
  - build
  - inspect

bitbake:
  stage: setup
  script:
    - source openembedded-core/oe-init-build-env
    # # Add the layers
    - bitbake-layers add-layer ../meta-raspberrypi
    - bitbake-layers add-layer ../meta-oe/meta-oe
    - bitbake-layers add-layer ../meta-oe/meta-python
    - bitbake-layers add-layer ../meta-oe/meta-filesystems
    - bitbake-layers add-layer ../meta-oe/meta-networking
    - bitbake-layers add-layer ../meta-go
    - bitbake-layers add-layer ../meta-virtualization
    - bitbake-layers add-layer ../meta-titania

    # Making sure config locations point where we want them to
    - echo 'SSTATE_DIR = "${TOPDIR}/sstate-cache"' >> ./conf/local.conf
    - echo 'DL_DIR = "${TOPDIR}/downloads"' >> ./conf/local.conf
    - echo 'TMPDIR = "${TOPDIR}/tmp"' >> ./conf/local.conf
    - echo 'DISTRO = "titania"' >> ./conf/local.conf
  artifacts:
    paths:
      - build
    expire_in: 1 day

# TODO: use Titania image classes here
# TODO: make new branches start out with fresh cache
raspberry:
  stage: build
  script:
    - source openembedded-core/oe-init-build-env
    - MACHINE="raspberrypi3" bitbake rpi-hwup-image
    - tree tmp-glibc/deploy/images
  cache:
    paths:
      - build/sstate-cache
      - build/downloads

desktop:
  stage: build
  script:
    - source openembedded-core/oe-init-build-env
    - bitbake core-image-minimal
    - tree tmp-glibc/deploy/images
  cache:
    paths:
      - build/sstate-cache
      - build/downloads

# TODO: remove me
images:
  stage: inspect
  script:
    - uname -a
